---
apiVersion: v1
kind: Service 
metadata:
  name: mediclaim-svc
  labels:
    app: mediclaim
spec:
  selector:
    app: mediclaim
  type: NodePort
  ports:
  - nodePort: 31113
    port: 8081
    targetPort: 8081 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediclaim
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mediclaim
  template:
    metadata:
      name: mediclaim
      labels:
        app: mediclaim
    spec:
      containers:
      - name: mediclaim
        image: narayudu/spring:6
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
