---
kind: Service
apiVersion: v1
metadata:
  name: spring
spec:
  selector:
    app: spring
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
  type: LoadBalancer  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediclaim
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mediclaim
  template:
    metadata:
      name: mediclaim
      labels:
        app: mediclaim
    spec:
      containers:
      - name: mediclaim
        image: narayudu/spring:6
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
